config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :categories
  resources :items
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/new_review', to: 'reviews#new'
  get    '/reviews',    to: 'reviews#index'
  get    '/about',      to: 'static_pages#about'
  get    '/new',        to: 'items#new'
  get    '/items',      to: 'items#index'
  get    'items_all',   to: 'items#all'
  get    'signup',      to: 'users#new'
  post   'signup',      to: 'users#create'
  get    '/login',      to: 'sessions#new'
  post   '/login',      to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  post   '/rent',       to: 'rentals#rent'
  post   '/checkin',    to: 'rentals#check_in'
  post   '/favorite',    to: 'favorites#favorite'
  delete '/favorite',    to: 'favorites#unfavorite'
  get    '/favorite_ajax_response', to: 'favorites#favorite_ajax_response'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category, required: false
  belongs_to :user,     required: false
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :top_item, dependent: :destroy

  validates :title, length: {minimum: 1}
  validates :description, length: {minimum: 1}
  validates :category_id, presence:  true
  validates :condition, presence:  true
  validates :price_hourly_usd, :inclusion => 0..99999, presence: true, unless: ->(item){item.price_daily_usd.present?}
  validates :price_daily_usd, :inclusion => 0..99999, presence: true, unless: ->(item){item.price_hourly_usd.present?}
  def self.conditions
    ['Like new', 'Almost new', 'Good', 'Decent', 'Ok', 'Barely Working 100%', 'Not working 100%']
  end

  def rating
    reviews.length != 0 ? reviews.sum(:rating) / reviews.length : 0
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_item,        only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user,  only: [:new, :create, :update, :destroy, :edit]
  before_action :user_owns_item,  only: [:edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @category = params[:category_search]
    @keyword  = params[:keyword_search]

    @items = Item
    if !@category.nil? && @category.length.positive?
      @items = @items.where(category_id: @category.to_i)
    end

    if !@keyword.nil? && @keyword.length.positive?
      @items = @items.where('LOWER(items.title) LIKE :keyword OR LOWER(items.description) LIKE :keyword', { keyword: "%#{@keyword.downcase}%" })
    end

    @items = @items.includes(:category).paginate(per_page: 20, page: params[:page])
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @reviews = Review.select { |review| review.item_id == @item.id }
    @review = Review.new(item_id: @item.id)
    @ratingSum = 0.0
    @reviews.each do |review|
      @ratingSum = @ratingSum + review.rating
    end
    @avgRating = (@ratingSum/@reviews.count).round(1)
    if logged_in?
      @isPrevRented = Rental.find_by(user_id: current_user.id, history: true, item_id: params[:id])
      @isPrevReviewed = Review.find_by(user_id: current_user, item_id: params[:id])
    end
    @rentals = Rental.where(item_id: params[:id], history: true)
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @category = Category.find_by(name: params[:category_id])
    @item = Item.new(item_params)
    @item.category_id = params[:item][:category_id]
    @item.available = true
    @item.user_id = @current_user.id
    @item.condition = params[:condition]
    @item.latitude = params[:user_lat]
    @item.longitude = params[:user_lng]

      if @item.save
        flash[:success] = "Item created"
        redirect_to item_path(@item)
      else
        flash[:danger] = "Failed"
        render 'items/new'
      end

  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
      flash[:success] = "Updated item"
      redirect_to item_path(@item)
    else
      render 'items/edit'
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    flash[:success] = "Item successfully destroyed"
    redirect_to items_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:title, :description, :available, :price_hourly_usd, :price_daily_usd)
  end

  def user_owns_item
    redirect_to root_path unless current_user?(@item.user)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  # Given a User id, return the display name of the User
  def get_display_name(review)
    if review.anonymous
      @display_name = 'Anonymous'
    else
      @user = User.find(review.user_id)
      @display_name = @user.display_name
    end
  end

  def display_category(category)
    category.nil? ? "Uncategorized" : category.name
  end

  # Method returns top n items based on sum of ratings
  def get_top_items(n: 10)
    items = Item.all.sort_by { |item| [item.rating * (item.reviews.length > 2 ? 1 : 0), item.reviews.length] }
    items.reverse!
    items[0..n]
  end

  def item_owned(user_id, item_user_id)
    if user_id == item_user_id
      true
    else
      false
    end

  end

  def item_rented(user_id, item_id)
    rental = Rental.where(user_id: user_id, item_id: item_id)
    if rental
      true
    else
      false
    end
  end

  def rental_length(start_date, end_date)

    seconds_diff = (start_date - end_date).to_i.abs

    days = (seconds_diff / 3600) / 24
    seconds_diff -= days * 24 * 3600

    hours = seconds_diff / 3600
    seconds_diff -= hours * 3600

    days_display = ""
    if days > 0
      days_display = "#{days.to_s.rjust(1, '0')} days, "
    end

    hours_display = ""
    if hours > 0
      hours_display = "#{hours.to_s.rjust(1, '0')} hours, "
    end

    minutes = seconds_diff / 60

    minutes_display = ""
    if minutes > 0
      minutes_display = "#{minutes.to_s.rjust(1, '0')} minutes"
    end


    seconds_diff -= minutes * 60

    seconds = seconds_diff
    seconds_display = "#{seconds.to_s.rjust(1, '0')}"

    days_display + hours_display + minutes_display


  end

  # Returns the keyword_search display
  def search_display
    @keyword_display = if !@keyword.nil? && @keyword.length.positive?
                         @keyword
                       else
                         'Search by Keyword'
                       end
  end

  def display_availability(availability)
    @available_display = if availability
                           'Available'
                         else
                           'Rented'
                         end
  end

  def cache_key_for_top_item(item)
    "item/#{item.top_item.id}/#{item.top_item.updated_at}/#{item.top_item.item_id}"
  end

  def cache_key_for_top_item_table
    "top_item_table/#{TopItem.maximum(:updated_at)}"
  end

  def cache_key_for_item(item)
    "item/#{item.id}/#{item.updated_at}/#{item.available}"
  end

  def cache_key_for_item_table
    "item_table/#{Item.maximum(:updated_at)}"
  end
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
<% if item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="field">
  <%= form.label :title, class: 'field_label' %>
  <%= form.text_field :title, class: 'text_field name' %>
</div>

<div class="field">
  <%= form.label :description, class: 'field_label' %>
  <%= form.text_area :description, class: 'text_field' %>
</div>

<div class="field">
  <%= form.label :category, class: 'field_label' %>
  <%= form.collection_select :category_id, Category.order(:name),:id,:name, include_blank: false %>

<div class="field">
  <%= form.label :condition, class: 'field_label' %>
  <%= select_tag(:condition, options_for_select(Item.conditions)) %>

</div>

</div>

<div class="field">
  <%= form.label :Hourly_Price, class: 'field_label' %>
  <%= form.text_field :price_hourly_usd, :placeholder => "Hourly Price (USD)", class: 'text_field name' %>
  <%= form.label :Daily_Price, class: 'field_label' %>
  <%= form.text_field :price_daily_usd, :placeholder => "Daily Price (USD)", class: 'text_field name' %>
</div>

<div id="map">
</div>
<input type="hidden" id="user_lat" name="user_lat" value="0">
<input type="hidden" id="user_lng" name="user_lng" value="0">

<script type="text/javascript">
    var map, infoWindow;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -34.397, lng: 150.644},
            zoom: 13
        });
        infoWindow = new google.maps.InfoWindow;

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                document.getElementById("user_lat").value = pos.lat;
                document.getElementById("user_lng").value = pos.lng;

                var infowindow = new google.maps.InfoWindow({
                    content: "Your position, yey"
                });

                var marker = new google.maps.Marker({
                    position: pos,
                    map: map,
                    title: 'Hello World!',
                    draggable: true,
                    id: 'current'
                });

                google.maps.event.addListener(marker, 'dragend', function(evt){
                    map.setCenter(marker.position);
                    marker.setMap(map);
                    document.getElementById("user_lat").value = marker.position.lat();
                    document.getElementById("user_lng").value = marker.position.lng();
                });


                marker.addListener('click', function() {
                    infowindow.open(map, marker);
                });

                marker.setMap(map);
                //moveBus( map, marker );


                //infoWindow.setPosition(pos);
                //infoWindow.setContent('Location found.');
                ///infoWindow.open(map);
                map.setCenter(pos);
            }, function() {
                handleLocationError(true, infoWindow, map.getCenter());
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false, infoWindow, map.getCenter());
        }
    }

    function moveBus( map, marker ) {

        marker.setPosition( new google.maps.LatLng( 0, 0 ) );
        map.panTo( new google.maps.LatLng( 0, 0 ) );

    }



    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
            'Error: The Geolocation service failed.' :
            'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
    }

    initMap();


</script>


<div class="actions">
  <%= form.submit class: 'submit_button' %>
</div>
<% end %>

app/views/items/_item.html.erb
<div class="list_item">
  <div class="fav_container" id="<%= item.id %>">
    <div class="list_item_button">
        <%= link_to image_tag("empty_star.png"), favorite_path(item_id: item.id), remote: true, method: :post %>
    </div>
  </div>
  <div class="text_container">

    <div class="list_item_text"><%= item.title %></div>
    <div class="list_item_text"><%= display_availability(item.available) %></div>
    <div class="list_item_text"><%= display_category(item.category) %></div>
  </div>
  <div class="button_container">
    <div class="list_item_button">
      <%= link_to 'Show', item, class: 'list_item_button action' %>
    </div>

    <div class="list_item_button">
      <button class="empty_btemplate">Show</button>
    </div>
  </div>
</div>

app/views/items/_item_header.html.erb
<div class="list_header">

  <div class="fav_container">

  </div>

  <div class="text_container">

    <p class="list_item_text header">Title</p>
    <p class="list_item_text header">Availability</p>
    <p class="list_item_text header">Category</p>
  </div>
  <div class="button_container">
    <div class="list_item_button">
      <button class="empty_btemplate">Show</button>
    </div>

    <div class="list_item_button">
      <button class="empty_btemplate">Show</button>
    </div>


  </div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<h3 align="center">What are you looking for?</h3>
<div class="search-input-group" align="center">
  <div class="form-inline search" align="center">
    <%= form_tag items_path, method: :get do %>
      <%= select_tag 'category_search', options_from_collection_for_select(Category.all, "id", "name", @category), include_blank: "All", onchange: "this.form.submit();"%>
      <%= text_field_tag('keyword_search', nil, :placeholder=> search_display, class: 'text_field name') %>
      <button type="submit" class="btn btn-primary">Search</button>
    <% end %>

  </div>
</div>

<hr>

<% cache ["page-#{params[:page]}/category-#{params[:category_search]}/keyword-#{params[:keyword_search]}/last_item-#{@items.last.nil? ? "nil" : @items.last.id}",
          @items.maximum('items.updated_at')] do %>

<%= will_paginate @items %>
<div class="item_table">
  <div class="table_content">
  <%= render 'item_header', owner: false %>
  </div>
  <div class="table_content">
    <% @items.each do |item| %>
      <% cache(cache_key_for_item(item)) do %>
        <%= render item %>
      <% end %>
    <% end %>
  </div>
</div>
<%= will_paginate @items %>

<% end %>

<script>
  <%= render partial: "favorites/favorite_ajax_request.js", locals: { items: @items } %>
</script>

app/views/items/new.html.erb
<h1>New Item</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', item: @item %>
    <%= link_to 'Back', items_path %>
  </div>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<div class="item_container">
  <h1 class="item_title"><%= @item.title %></h1>

  <div class="item_sub_container">
    <p>
      <strong>Rating:</strong>
      <% if @reviews.count > 0 %>
        <%= @avgRating %>/5 based on <%= @reviews.count %> review(s)
        <% else %>
        No rating yet.
        <% end %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @item.description %>
    </p>
    <p>
      <strong>Condition:</strong>
      <%= @item.condition %>
    </p>

    <% if @item.price_hourly_usd != nil %>
    <p>
      <strong>Hourly price USD:</strong>
      <%= @item.price_hourly_usd %>
    </p>
    <% end %>

    <% if @item.price_daily_usd != nil %>
    <p>
      <strong>Daily price USD:</strong>
      <%= @item.price_daily_usd %>
    </p>
    <% end %>


    <p>
      <strong>Available:</strong>
      <% if @item.available %>
        Yes
      <% else %>
        No
      <% end %>
    </p>

    <% unless current_user.nil? %>
      <% if @item.available and !item_owned(current_user.id, @item.user_id) %>

        <%= link_to 'Rent',
                    rent_path(item_id: @item),
                    method: :post,
                    data: { confirm: 'Are you sure you want to rent?', item: @item },
                    class: 'primary_button'
        %>

      <% elsif !@item.available and item_rented(current_user.id, @item.id) %>
        <%= link_to 'Check in item',
                    checkin_path(item_id: @item),
                    method: :post,
                    data: { confirm: 'Are you sure you want to check in the item?', item: @item },
                    class: 'primary_button'
        %>
      <% end %>
    <% end %>


    <div class="bottom_buttons">
      <% unless current_user.nil? or !item_owned(current_user.id, @item.user_id) %>
        <%= link_to 'Edit', edit_item_path(@item) ,class: "primary_button light"%>
        <%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: "primary_button light" %>
      <% end %>
      <%= link_to 'Back', items_path ,class: "primary_button light"%>
      <%if  @isPrevRented and !@isPrevReviewed %>
      <button class="primary_button light" data-toggle="collapse" data-target="#review">Write a review</button>
      <% end %>
    </div>

  </div>


</div>


<%if  @isPrevRented and !@isPrevReviewed %>
  <div id="review" class="collapse">
    <div class="review_container">
      <%= render 'reviews/form', review: @review %>
    </div>
  </div>
<% end %>


<div id="map-container">
  <div id="map">
  </div>
</div>


<input type="hidden" id="item_lat" name="item_lat" value='<%= @item.latitude %>'>
<input type="hidden" id="item_lng" name="item_lng" value='<%= @item.longitude %>'>

<script type="text/javascript">
    var map, infoWindow;
    function initMap() {

        var latitude = parseFloat(document.getElementById("item_lat").value);
        var longitude = parseFloat(document.getElementById("item_lng").value);

        console.log('COMING Lat');
        console.log(latitude);

        var pos = {
            lat: latitude,
            lng: longitude
        };

        map = new google.maps.Map(document.getElementById('map'), {
            center: {
                lat: latitude,
                lng: longitude
            },
            zoom: 13
        });

        var infowindow = new google.maps.InfoWindow({
            content: "Items position"
        });

        var marker = new google.maps.Marker({
            position: pos,
            map: map,
            title: 'Hello!'
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });

        marker.setMap(map);
    }

    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
            'Error: The Geolocation service failed.' :
            'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
    }

    initMap();


</script>


<hr>

<h2 id="reviews_title">Reviews</h2>

<div class="item_table">
  <% if @reviews.count != 0 %>
  <div class="table_content">

    <div class="list_header">

      <div class="text_container">
        <p class="list_item_text header">Title</p>
        <p class="list_item_text header">Review</p>
        <p class="list_item_text header">Rating</p>
        <p class="list_item_text header">User</p>
      </div>
    </div>
  </div>
  <% else %>
    <div id="no_review_container">
      <h4 id="no_reviews_title">No reviews to show!</h4>
    </div>
  <% end %>

  <div class="table_content">

    <% @reviews.each do |review| %>

      <div class="list_item">
        <div class="text_container">
          <p class="list_item_text"><%= review.title %></p>
          <p class="list_item_text"><%= review.body %></p>
          <p class="list_item_text">
            <% review.rating.to_i.times do  %>
              <span class="glyphicon glyphicon-star"></span>
            <% end %>
            <% (5-review.rating).to_i.times do %>
              <span class="glyphicon glyphicon-star-empty"></span>
            <% end %>
          </p>
          <p class="list_item_text"><%= get_display_name(review) %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>


<h2 id="reviews_title">Rentals</h2>

<div class="item_table">
  <% if @rentals.count != 0 %>
    <div class="table_content">

    <div class="list_header">

      <div class="text_container">
        <p class="list_item_text header">Name</p>
        <p class="list_item_text header">Rental length</p>
        <p class="list_item_text header">Check-in date</p>
      </div>
    </div>
    </div>
  <% else %>
    <div id="no_review_container">
      <h4 id="no_reviews_title">No rentals to show!</h4>
    </div>
  <% end %>

  <div class="table_content">

  <% @rentals.each do |rental| %>

    <div class="list_item">
      <div class="text_container">
        <p class="list_item_text"><%= display_renter_title(rental) %></p>
        <p class="list_item_text"><%= rental_length(rental.created_at, rental.check_in_date) %></p>
        <p class="list_item_text"><%= rental.check_in_date %></p>
      </div>
    </div>
  <% end %>
  </div>
</div>