config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :categories
  resources :items
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/new_review', to: 'reviews#new'
  get    '/reviews',    to: 'reviews#index'
  get    '/about',      to: 'static_pages#about'
  get    '/new',        to: 'items#new'
  get    '/items',      to: 'items#index'
  get    'items_all',   to: 'items#all'
  get    'signup',      to: 'users#new'
  post   'signup',      to: 'users#create'
  get    '/login',      to: 'sessions#new'
  post   '/login',      to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  post   '/rent',       to: 'rentals#rent'
  post   '/checkin',    to: 'rentals#check_in'
  post   '/favorite',    to: 'favorites#favorite'
  delete '/favorite',    to: 'favorites#unfavorite'
  get    '/favorite_ajax_response', to: 'favorites#favorite_ajax_response'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user,  only: [:new, :create, :update, :destroy, :edit]
  before_action :user_owns_review,  only: [:update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    if logged_in?
      @review = Review.new
    else
      flash[:danger] = "Only authenticated users can create reviews"
      redirect_to login_path
    end
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id

    if @review.save
      flash[:success] = "Added review"
      redirect_to Item.find(@review.item_id)
    else
      flash[:danger] = "Review failed"
      redirect_to Item.find(@review.item_id)
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    if @review.update(review_params)
      flash[:success] = "Upated review"
      redirect_to @current_user || root_path
    else
      flash[:danger] = "Review failed"
      render 'edit'
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    flash[:success] = "Review deleted"
    RatingsCalculatorJob.perform_later
    redirect_to @current_user || root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:item_id, :title, :body, :rating, :user_id, :anonymous)
    end

    def user_owns_review
      redirect_to root_path unless current_user?(@review.user)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def display_item_title(review)
    @item_title = Item.find_by(id: review.item_id).title
  end
end

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field invisible" >
    <%= form.label :item_id, class: 'field_label' %>
    <%= form.collection_select :item_id, Item.order(:title),:id,:title, include_blank: false %>
  </div>

  <h3 class="subtitle">Write a new review</h3>

  <div class="field">
    <%= form.label :title, class: 'field_label' %>
    <%= form.text_field :title, class: 'text_field name' %>
  </div>

  <div class="field">
    <%= form.label :body, class: 'field_label' %>
    <%= form.text_area :body, class: 'text_field' %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.select :rating, options_for_select(1..5),include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :anonymous %>
    <%= form.check_box :anonymous %>
  </div>

  <div class="actions">
    <%= form.submit class: 'submit_button' %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="list_item">
  <div class="text_container">
    <p class="list_item_text"><%= display_item_title(review) %></p>
    <p class="list_item_text"><%= review.title %></p>
    <p class="list_item_text">
      <% review.rating.to_i.times do  %>
        <span class="glyphicon glyphicon-star"></span>
      <% end %>
      <% (5-review.rating).to_i.times do %>
        <span class="glyphicon glyphicon-star-empty"></span>
      <% end %>
    </p>
  </div>
  <div class="button_container">
    <div class="list_item_button">
      <%= link_to 'Show', item_path(review.item_id), class: 'list_item_button action' %>
    </div>

    <% if current_user?(review.user) %>
      <div class="list_item_button">
        <%= link_to 'Edit', edit_review_path(review), class: 'list_item_button action' %>
      </div>
      <div class="list_item_button">
        <%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }, class: 'list_item_button action delete' %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_review_header.html.erb
<div class="list_header">
  <div class="text_container">
    <p class="list_item_text header">Item</p>
    <p class="list_item_text header">Review title</p>
    <p class="list_item_text header">Rating</p>
  </div>
  <div class="button_container">

  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Title</th>
      <th>Body</th>
      <th>Rating</th>
      <th>User</th>
      <th>Anonymous</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.item_id %></td>
        <td><%= review.title %></td>
        <td><%= review.body %></td>
        <td><%= review.rating %></td>
        <td><%= review.user_id %></td>
        <td><%= review.anonymous %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @review.item_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Anonymous:</strong>
  <%= @review.anonymous %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>