config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :categories
  resources :items
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/new_review', to: 'reviews#new'
  get    '/reviews',    to: 'reviews#index'
  get    '/about',      to: 'static_pages#about'
  get    '/new',        to: 'items#new'
  get    '/items',      to: 'items#index'
  get    'items_all',   to: 'items#all'
  get    'signup',      to: 'users#new'
  post   'signup',      to: 'users#create'
  get    '/login',      to: 'sessions#new'
  post   '/login',      to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  post   '/rent',       to: 'rentals#rent'
  post   '/checkin',    to: 'rentals#check_in'
  post   '/favorite',    to: 'favorites#favorite'
  delete '/favorite',    to: 'favorites#unfavorite'
  get    '/favorite_ajax_response', to: 'favorites#favorite_ajax_response'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://github.com/scalableinternetservices/Podz">amazing podz rental service</a>
    by <a href="https://github.com/scalableinternetservices/Podz">podz</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "PODZ", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Items",    items_path %></li>
        <% if admin? %>
          <li> <%= link_to "Categories", categories_path%></li>
        <% end %>
        <% if logged_in? %>
          <li> <%= link_to "New Item",    new_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyCheZe0VeXhxSIiVUpX_-RQxeR3YpJ4SYw"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>